[package]
name = "rabbit_trading_api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
dotenv = { workspace = true }
log = { workspace = true }
rabbit_trading_core = { path = "../core" }
serde = { workspace = true, features = ["derive"] }
simple_logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]

[features]
