[workspace]
members = [
    "packages/ibkr_client_portal",
    "packages/main",
]

[workspace.dependencies]
async-trait = "0.1.77"
dogstatsd = "0.11.1"
dotenv = "0.15.0"
futures-util = "0.3.30"
log = "0.4.20"
longbridge = "0.2.77"
reqwest = "0.11.23"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
serde = "1.0.195"
serde_json = "1.0.111"
serde_repr = "0.1.18"
serde_yaml = "0.9.30"
simple_logger = "4.3.3"
tempfile = "3.9.0"
time = "0.3.31"
tokio = "1.35.1"
tokio-tungstenite = "0.21.0"
tokio-test = "0.4.3"
yahoo_finance_api = "2.1.0"
