[package]
name = "rabbit_trading"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
log = "0.4.20"
longbridge = "0.2.77"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
simple_logger = "4.3.0"
time = { version = "0.3.31", features = ["parsing", "macros", "formatting"] }
tokio = { version = "1.35.0", features = ["full"] }
yahoo_finance_api = "2.1.0"

[dev-dependencies]
tokio-test = "0.4.3"

[features]
full = ["long_bridge", "yahoo_finance", "interactive_brokers"]
default = ["full"]
ci = ["full"]
long_bridge = []
yahoo_finance = []
interactive_brokers = []
