[package]
name = "ibkr_client_portal"
version = "0.0.5"
edition = "2021"
description = "Unofficial API Client implement for Interactive brokers (IBKR) Client Portal."
repository = "https://github.com/ttzztztz/rabbit_trading"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rust_decimal = { workspace = true, features = ["maths", "serde-float", "serde-with-str"] }
rust_decimal_macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["parsing", "macros", "formatting", "serde"] }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }

[dev-dependencies]
dotenv = { workspace = true }
serial_test = { workspace = true }

[features]
ci = []
flaky_test_cases = []
