[package]
name = "ibkr_client_portal"
version = "0.3.3"
edition = "2021"
authors = ["Rabbit <ttzztztz@outlook.com>"]
description = "Unofficial API Client implement for Interactive Brokers (IBKR / IB) Client Portal."
repository = "https://github.com/ttzztztz/rabbit_trading"
license = "MIT"
keywords = ["ib", "ibkr", "ibcp", "interactive-brokers"]
categories = ["api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
mixin = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true, features = ["json"] }
reqwest-retry = { workspace = true }
rust_decimal = { workspace = true, features = ["maths", "serde-float", "serde-with-str"] }
rust_decimal_macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }

[dev-dependencies]
async_once = { workspace = true }
dotenv = { workspace = true }
lazy_static = { workspace = true }
serial_test = { workspace = true }

[features]
full = ["streaming"]
default = ["full"]
ci = []
flaky_test_cases = []
streaming = []
