[package]
name = "ibkr_client_portal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rust_decimal = { workspace = true, features = ["maths", "serde-float", "serde-with-str"] }
rust_decimal_macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }

[dev-dependencies]
dotenv = { workspace = true }

[features]
ci = []
