name: Cargo Publish

on:
  push:
    branches:
      - master
    paths:
      - "packages/ibkr_client_portal/Cargo.toml"
      - ".github/workflows/cargo-publish.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          path: "./packages/ibkr_client_portal"
          registry-token: ${{ secrets.CARGO_PUBLISH_TOKEN }}
          ignore-unpublished-changes: true
