name: Docker Image CI (Push)

on:
  push:
    branches:
      - master
    paths:
      - "dockerfiles/**"
      - ".github/workflows/docker-**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/ibkr_client_portal/Dockerfile
          push: true
          tags: |
            ttzztztz/ibkr_client_portal:latest
            ttzztztz/ibkr_client_portal:${{ github.sha }}
